Revert "Checkout to the correct branch in with_checkout."
This reverts commit ef24ca346f0ae217da23d41286b841afe7a81a8d, which
causes checkouts to fail with e.g.

    error: pathspec 'refs/pull/449/head' did not match any file(s) known to git