Fix type error in line-numbers
Eager to silent a jshint warning,

> error: Functions declared within loops referencing an outer scope
> variable may lead to confusing semantics. (W083)

I introduced an incorrect little change in
b50b9578ac986ff12b9649fe2ab940cc9c10028f, which led to errors reported
in browsers:

> Uncaught TypeError: debounceTimerFn is not a function
>   mutationCallback https://tezos.ci.dev/js/line-numbers.js:74